# Autogenerated wrapper script for EPANET_jll for i686-linux-musl
export libepanet, libepanet_output, runepanet

JLLWrappers.@generate_wrapper_header("EPANET")
JLLWrappers.@declare_library_product(libepanet, "libepanet2.so")
JLLWrappers.@declare_library_product(libepanet_output, "libepanet-output.so")
JLLWrappers.@declare_executable_product(runepanet)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libepanet,
        "lib/libepanet2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepanet_output,
        "lib/libepanet-output.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        runepanet,
        "bin/runepanet",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
