# Autogenerated wrapper script for EPANET_jll for x86_64-apple-darwin
export libepanet, libepanet_output, runepanet

JLLWrappers.@generate_wrapper_header("EPANET")
JLLWrappers.@declare_library_product(libepanet, "@rpath/libepanet2.dylib")
JLLWrappers.@declare_library_product(libepanet_output, "@rpath/libepanet-output.dylib")
JLLWrappers.@declare_executable_product(runepanet)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libepanet,
        "lib/libepanet2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepanet_output,
        "lib/libepanet-output.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        runepanet,
        "bin/runepanet",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
