# Autogenerated wrapper script for EPANET_jll for x86_64-w64-mingw32
export libepanet, libepanet_output, runepanet

JLLWrappers.@generate_wrapper_header("EPANET")
JLLWrappers.@declare_library_product(libepanet, "libepanet2.dll")
JLLWrappers.@declare_library_product(libepanet_output, "libepanet-output.dll")
JLLWrappers.@declare_executable_product(runepanet)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libepanet,
        "bin\\libepanet2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepanet_output,
        "bin\\libepanet-output.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        runepanet,
        "bin\\runepanet.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
